"use strict";

module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_ERROR: "AUTH_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  API_KEY_INVALID: "API_KEY_INVALID",
  INTERNAL_ERROR: "INTERNAL_ERROR"
};
